<a href="https://colab.research.google.com/github/VSharma27/Weather-App/blob/main/dangi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

demand = np.array([15,16,17,18,19])

In [2]:
probability = np.array([0.15,0.25,0.4,0.15,0.05])

In [3]:
profit=20
loss=80
shortage_cost=40

In [15]:
payoff = np.array([[0,0,0,0,0], [0,0,0,0,0], [0,0,0,0,0], [0,0,0,0,0], [0,0,0,0,0]])

for i in range(0,5):
  for j in range(0,5):
    if(demand[j]==demand[i]):
      #print("demand matched")
      payoff[i][j]=demand[i]*20
      print(payoff[i][j])
    elif(demand[j]<=demand[i]):
      #print("demand LESS")
      payoff[i][j]=demand[j]*20-(demand[i]-demand[j])*80
      print(payoff[i][j])
    else:
      #print("demand greater")
      payoff[i][j]=demand[i]*20-(demand[j]-demand[i])*40
      print(payoff[i][j])


      


300
260
220
180
140
220
320
280
240
200
140
240
340
300
260
60
160
260
360
320
-20
80
180
280
380


In [16]:
for x in payoff:
  print(x)

[300 260 220 180 140]
[220 320 280 240 200]
[140 240 340 300 260]
[ 60 160 260 360 320]
[-20  80 180 280 380]
